import 'package:flutter/material.dart';

import '../../models/video_data.dart';

Stack videoItemArea(
    BuildContext context, AsyncSnapshot<Autogenerated> snapshot, int index) {
  return Stack(
    children: [
      ClipRRect(
        borderRadius: const BorderRadius.only(
            topLeft: Radius.circular(10), topRight: Radius.circular(10)),
        child: SizedBox(
          height: MediaQuery.of(context).size.height * .25,
          width: MediaQuery.of(context).size.width,
          child: Image.network(
            snapshot.data!.results![index].thumbnail!,
            fit: BoxFit.fill,
          ),
        ),
      ),
      Positioned(
        bottom: 10,
        right: 10,
        child: Container(
          padding: const EdgeInsets.all(5),
          decoration: const BoxDecoration(
            color: Colors.black,
            borderRadius: BorderRadius.all(Radius.circular(10)),
          ),
          child: Text(
            snapshot.data!.results![index].duration!,
            style: const TextStyle(color: Colors.white),
          ),
        ),
      )
    ],
  );
}
