import 'package:flutter/foundation.dart';

import '../../models/video_data.dart';

class HomePageProvider extends ChangeNotifier {
  List<Autogenerated> _files = [];

  List<Autogenerated> get files => _files;

  void setFiles({required Autogenerated value}) {
    _files.clear();
    _files.add(value);
    notifyListeners();
  }
}
